service: owntracks
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  memorySize: 256
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-central-1'}
  logRetentionInDays: 7

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
            - "sqs:ReceiveMessage"
          Resource:
            Fn::GetAtt: [ SQSLocation, Arn ]
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:BatchWriteItem"
          Resource:
            Fn::GetAtt: [ DynamoDBLocationTable, Arn ]

package:
  individually: true

functions:
  receiver:
    handler: bootstrap
    package:
      artifact: build/receiver.zip
    environment:
      SQS_LOCATION_URL:
        Ref: SQSLocation
    events:
      - httpApi:
          path: /
          method: post
      - httpApi:
          path: /report
          method: post

  writer:
    handler: bootstrap
    package:
      artifact: build/writer.zip
    environment:
      DB_LOCATION_NAME: ${self:service}-location-${sls:stage}
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ SQSLocation, Arn ]

resources:
  Resources:
    DynamoDBLocationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-location-${sls:stage}
        AttributeDefinitions:
          - AttributeName: tid
            AttributeType: S
          - AttributeName: tst
            AttributeType: N
        KeySchema:
          - AttributeName: tid
            KeyType: HASH
          - AttributeName: tst
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    SQSLocation:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-location-${sls:stage}
        MessageRetentionPeriod: 604800
        VisibilityTimeout: 60
        DelaySeconds: 30
