service: owntracks
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  memorySize: 256
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-central-1'}
  logRetentionInDays: 7

  logs:
    httpApi: true
  
  apiGateway:
    metrics: true

  httpApi:
    authorizers:
      agentAuthorizer:
        type: request
        identitySource:
          - $request.header.Authorization
        enableSimpleResponses: true
        resultTtlInSeconds: 0
        functionArn: arn:aws:lambda:${self:provider.region}:966137286427:function:${self:service}-${self:provider.stage}-auth

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
            - "sqs:ReceiveMessage"
          Resource:
            Fn::GetAtt: [ SQSLocation, Arn ]
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:BatchWriteItem"
          Resource:
            Fn::GetAtt: [ DynamoDBLocationTable, Arn ]
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:eu-central-1:966137286427:secret:owntracks/prod/*"

package:
  individually: true

functions:
  auth:
    handler: bootstrap
    package:
      artifact: build/auth.zip
    environment:
      SECRET_ID: owntracks/prod/auth

  receiver:
    handler: bootstrap
    package:
      artifact: build/receiver.zip
    environment:
      SQS_LOCATION_URL:
        Ref: SQSLocation
    events:
      - httpApi:
          path: /
          method: post
      - httpApi:
          path: /owntracks/report
          method: post
          authorizer:
            name: agentAuthorizer

  writer:
    handler: bootstrap
    package:
      artifact: build/writer.zip
    environment:
      DB_LOCATION_NAME: ${self:service}-location-${sls:stage}
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ SQSLocation, Arn ]

resources:
  Resources:
    DynamoDBLocationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-location-${sls:stage}
        AttributeDefinitions:
          - AttributeName: tid
            AttributeType: S
          - AttributeName: tst
            AttributeType: N
        KeySchema:
          - AttributeName: tid
            KeyType: HASH
          - AttributeName: tst
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    SQSLocation:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-location-${sls:stage}
        MessageRetentionPeriod: 604800
        VisibilityTimeout: 60
        DelaySeconds: 30
